config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'test/index'
  get 'test/show'
  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'

  resources :subjects do
    member do
      get :delete
    end
  end

end

app/models/page.rb
class Page < ActiveRecord::Base

  belongs_to :subjects
  has_many :sections
  has_and_belongs_to_many :users

end

app/models/section.rb
class Section < ActiveRecord::Base

  belongs_to :page
  
end

app/models/subject.rb
class Subject < ActiveRecord::Base

  has_many :pages

end

app/models/user.rb
class User < ActiveRecord::Base

  self.table_name = "admin_users"

  has_and_belongs_to_many :pages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false

  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
    render('hello') # renders template
  end

  def other_hello
    redirect_to(:controller => 'demo', :action => 'hello') # new page
  end

  def lynda
    redirect_to('http://lynda.com')
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.order(:position)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      redirect_to(subjects_path(@subject))
    else
      render('edit')
    end
  end

  def delete
  end

  def destroy
  end

  private
    def subject_params
      params.require(:subject).permit(:name, :position, :visible)
    end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/demo/hello.html.erb
<h1>Hello World from hello</h1>

<%= 1 + 1 %>

<br/>

<% target = "world" %>
<%= "Hello #{target}" %>

<br/>

<% @array.each do |n| %>
  <%= n %> <br/>
<% end %>


<hr/>

<%= link_to("Index Page", {:action => "index"}) %>

<br />

ID: <%= @id %><br />
ID: <%= params[:id] %><br />
Page: <%= @page %><br />
Next Page: <%= @page.to_i + 1 %><br />

app/views/demo/index.html.erb
<h1>Hello World from index</h1>

<a href="/demo/hello">Hello Page 1</a>

<hr/>

<%= link_to("Hello Page 2", {:action => "hello"}) %>

<hr/>

<%= link_to("Hello with Parameters", {:action => "hello", :page => 5, :id => 20}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>

</div>

app/views/subjects/index.html.erb
<div class="subjects index">

  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => "action new") %>

  <table class="listing" summary="Subject List">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => "action show") %>
        <%= link_to("Edit", edit_subject_path(subject), :class => "action edit") %>
        <%= link_to("Delete", "#", :class => "action delete") %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.text_field(:position) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>

</div>

app/views/subjects/show.html.erb
<%= link_to("<< Back to list", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>